/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

// Set Kotlin JVM target to 17
kotlin {
    jvmToolchain(17)
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation("com.google.protobuf:protobuf-gradle-plugin:0.9.5")
    implementation("com.diffplug.spotless:spotless-plugin-gradle:8.1.0")
    implementation("com.vanniktech:gradle-maven-publish-plugin:0.35.0")
}
