name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and Test
        run: ./gradlew build test

      - name: Conformance Tests
        run: make test-conformance-stable