name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

  conformance:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - name: Netty
            args: --build-arg config=suite-netty.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run conformance tests for ${{ matrix.config.name }}
        run: docker build -f build/conformance/Dockerfile . --progress=plain ${{ matrix.config.args }}
