name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Test
        run: gradle build test

  conformance:
    name: Conformance Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - name: Netty server
            profile: netty-server
          - name: Netty server non-stable
            profile: netty-server-nonstable
          - name: Netty client
            profile: netty-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run conformance tests for ${{ matrix.config.name }}
        run: make test-conformance PROFILE=${{ matrix.config.profile }}
