name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: gradle build

      - name: Test
        run: gradle test

  conformance:
    name: Conformance Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - name: Netty
            args: --build-arg config=suite-netty.yaml
          - name: Netty non-stable
            args: --build-arg config=suite-netty-nonstable.yaml --build-arg stable=false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run conformance tests for ${{ matrix.config.name }}
        run: docker build -f conformance-build/Dockerfile . --progress=plain ${{ matrix.config.args }}

  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest

    needs: [build, conformance]
    environment: "publish"

    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up build scan
        uses: bmuschko/setup-gradle-public-build-scan@v1

      - name: Publish to Maven Central
        run: gradle publish --scan

        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
