name: Publish

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: "publish"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        #with:
        #  build-scan-publish: true
        #  build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
        #  build-scan-terms-of-use-agree: 'yes'

      # https://vanniktech.github.io/gradle-maven-publish-plugin/central/
      - name: Publish to Maven Central
        run: gradle publish --no-configuration-cache #--scan

        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}